version: '3.8'

networks:
  nextcloud:
    driver: bridge
    name: nextcloud
  moodle:
    driver: bridge
    name: moodle

services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    restart: unless-stopped
    networks:
      - nextcloud
      - moodle
    volumes:
      - clam:/var/lib/clamav
      - claml:/var/log/clamav

volumes:
  clam:
  claml: